services:

  frontend:
    container_name: frontend
    build:
      context: frontend/
    networks:
      - transcendence
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
      - SUPABASE_URL=https://yjhcivcuyvdvnvulezbm.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqaGNpdmN1eXZkdm52dWxlemJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDEwODksImV4cCI6MjA3NTY3NzA4OX0.iLA7ecRqK444Q8jDPdpvVBvkyKqbD60AkO3a8uEJWoo

    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend/src/
          target: /app/src/
        - action: sync
          path: ./frontend/public/
          target: /app/public/
          ignore:
            - app/public/dist/*.js
        - action: rebuild
          path: ./frontend/*.json
          target: app/

networks:
  transcendence:
    name: transcendence
    driver: bridge