services:
  frontend:
    container_name: frontend
    build:
      context: frontend/
    networks:
      - transcendence
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend/src/
          target: /app/src/
        - action: sync
          path: ./frontend/public/
          target: /app/public/
          ignore:
            - app/public/dist/*.js
        - action: rebuild
          path: ./frontend/*.json
          target: app/
  user-management:
    container_name: user-management
    build:
      context: services/user-management/
    networks:
      - transcendence
    ports:
      - "5000:5000"         #DEV
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/user-management/src/
          target: /app/src/
        - action: rebuild
          path: ./services/user-management/package.json
          target: /app/

  match-server:
    container_name: match-server
    build:
      context: services/match-server/
    networks:
      - transcendence
    ports:
      - "4443:4443"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/match-server/src/
          target: /app/src/
        - action: rebuild
          path: ./services/match-server/package.json
          target: /app/

  tower-defense:
    container_name: tower-defense
    build:
      context: services/tower-defense/
    networks:
      - transcendence
    ports:
      - "2246:2246"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/tower-defense/src/
          target: /app/src/
        - action: rebuild
          path: ./services/tower-defense/package.json
          target: app/

  social:
    container_name: social
    build:
      context: services/social/
    networks:
      - transcendence
    ports:
      - "6500:6500"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/social/src/
          target: /app/src/
        - action: rebuild
          path: ./services/social/package.json
          target: app/

  tournament:
    container_name: tournament
    build:
      context: services/tournament/
    networks:
      - transcendence
    ports:
      - "7000:7000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./services/tournament/src/
          target: /app/src/
        - action: rebuild
          path: ./services/tournament/package.json
          target: app/

  # ai-opponent:
  #  container_name: ai-opponent
  #  build:
  #    context: services/ai-opponent/
  #  networks:
  #    - transcendence
  #  restart: unless-stopped

networks:
  transcendence:
    name: transcendence
    driver: bridge