services:
  frontend:
    container_name: frontend
    build:
      context: frontend/
    networks:
      - transcendence
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped

  user-management:
    container_name: user-management
    build:
      context: services/user-management/
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    volumes:
      - ./data/user-management:/app/db
    restart: unless-stopped

  pong:
    container_name: pong
    build:
      context: services/pong/
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped

  tower-defense:
    container_name: tower-defense
    build:
      context: services/tower-defense/
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped

  social:
    container_name: social
    build:
      context: services/social/
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped

  tournament:
    container_name: tournament
    build:
      context: services/tournament/
    networks:
      - transcendence
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY:-""}
    restart: unless-stopped

  ai-opponent:
    container_name: ai-opponent
    build:
      context: services/ai-opponent/
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    name: transcendence
    driver: bridge