services:
  back:
    build:
      context: requirements/node
    container_name: trns_back_1
    environment:
      - NODE_ENV=production
    ports:
      - "8081:8081"
    networks:
      - comm

networks:
  comm:
    driver: bridge